language: node_js
node_js:
  - "4"
  - "6"
  - "8"

before_install:
    - npm install grunt-cli -g
    - stty cols 80

dist: trusty
sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
